# Generated by Django 3.1.1 on 2022-02-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('workerId', models.TextField(default='')),
                ('get_args', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('ua_header', models.TextField(default='')),
                ('screen_width', models.TextField(default='')),
                ('screen_height', models.TextField(default='')),
                ('captcha_score', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('native_english', models.BooleanField(blank=True, null=True)),
                ('post_test_purpose', models.TextField(default='')),
                ('post_test_other', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=80)),
                ('item', models.IntegerField()),
                ('item_type', models.CharField(max_length=80)),
                ('trial_index', models.IntegerField()),
                ('answer', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlm_fb_expt.participant')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionCheckTrial',
            fields=[
                ('trial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nlm_fb_expt.trial')),
            ],
            bases=('nlm_fb_expt.trial',),
        ),
        migrations.CreateModel(
            name='CriticalTrial',
            fields=[
                ('trial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nlm_fb_expt.trial')),
                ('condition', models.CharField(max_length=80)),
                ('first_mention', models.CharField(max_length=80)),
                ('recent_mention', models.CharField(max_length=80)),
                ('knowledge_cue', models.CharField(max_length=80)),
                ('start', models.CharField(max_length=80)),
                ('end', models.CharField(max_length=80)),
                ('is_start', models.BooleanField(blank=True, null=True)),
                ('is_end', models.BooleanField(blank=True, null=True)),
                ('passage_reading_time', models.FloatField()),
            ],
            bases=('nlm_fb_expt.trial',),
        ),
    ]
