# Generated by Django 3.1.1 on 2022-02-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm_fb_expt', '0003_participant_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionchecktrial',
            name='question_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
