# Generated by Django 3.1.1 on 2022-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm_fb_expt', '0004_attentionchecktrial_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='workerId',
            new_name='assignment_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='worker_id',
            field=models.TextField(default=''),
        ),
    ]
