# Generated by Django 3.1.1 on 2022-03-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm_fb_expt', '0005_auto_20220217_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='adhd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='asd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='dyslexia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
