# Generated by Django 3.1.1 on 2022-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlm_fb_expt', '0006_auto_20220304_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='vision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_reason',
            field=models.TextField(default=''),
        ),
    ]
